# Generated by Django 5.2.3 on 2025-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINAL', 'Final')], default='SCHEDULED', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
