# Generated by Django 5.2.3 on 2025-11-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='assigned_coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_children', to=settings.AUTH_USER_MODEL),
        ),
    ]
